websocket:
  port: 9091
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logout:
  hosts:
    - http://localhost:8081
    - http://localhost:8082
