websocket:
  port: 9090
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    root: info

