websocket:
  port: 9092
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logout:
  hosts:
    - http://localhost:8080
#    - http://localhost:8082
server:
  port: 8081
